#!/usr/bin/env python3
"""
fetch_corpus.py - BUILD-TIME ONLY. `run_demo.py` never calls this and never touches the network.

Pulls a bounded slice of seven public datasets, one per training lane, writes each to
`frozen/corpus/<lane>.jsonl`, and records source, licence, document count, byte count and
sha256 in `frozen/corpus/SOURCES.json`.

The output is COMMITTED to the repository. That is the whole point: the grader clones and runs
one command, so every input the demo needs must already be on disk. `run_demo.py` verifies the
recorded hashes and aborts on mismatch.

Determinism rules this script obeys, because the shards built from its output must be immutable:
  * documents are taken in stream order and never shuffled;
  * caps are byte caps, applied identically every run;
  * each line is written with sorted keys and no incidental whitespace;
  * document ids are content-addressed, so the same text always yields the same id.

Licences are recorded per lane in SOURCES.json and in the repository's NOTICE.md. The code lane
is filtered to permissive licences only - see PERMISSIVE below.

Usage:  python fetch_corpus.py [lane ...]        (default: all lanes)
"""
import hashlib
import io
import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "frozen", "corpus")
os.makedirs(OUT, exist_ok=True)
os.environ.setdefault("HF_HOME", os.path.join(HERE, ".hf_cache"))

# Byte caps on raw text per lane. Small on purpose: the brief asks for a demonstration, and the
# instructor asked not to be made to download a large dataset.
CAPS = {
    "web": 3_000_000,
    "code": 3_000_000,
    "math": 2_000_000,
    "reasoning": 1_500_000,
    "indic": 3_000_000,
    "agentic": 2_000_000,
    "long_ctx": 3_000_000,
}

# The code lane keeps only these. codeparrot-clean-valid also carries gpl-2.0, gpl-3.0 and
# agpl-3.0 files; redistributing copyleft source from an MIT repository is a licence conflict,
# so those files are dropped at fetch time rather than filtered later.
PERMISSIVE = {"mit", "apache-2.0", "bsd-2-clause", "bsd-3-clause", "isc"}

# Per-lane provenance recorded into SOURCES.json.
LICENCES = {
    "web": ("Salesforce/wikitext (wikitext-103-raw-v1)", "CC BY-SA 3.0/4.0"),
    "code": ("codeparrot/codeparrot-clean-valid (permissive-filtered)", "per-file: MIT/Apache-2.0/BSD/ISC"),
    "math": ("open-web-math/open-web-math", "ODC-By 1.0 (Common Crawl ToU applies)"),
    "reasoning": ("openai/gsm8k (main)", "MIT"),
    "indic": ("ai4bharat/indic-align (Anudesh, Dolly_T, WikiHow)", "CC BY 4.0"),
    "agentic": ("glaiveai/glaive-function-calling-v2", "Apache-2.0"),
    "long_ctx": ("Project Gutenberg", "Public domain in the US"),
}

# Indic languages we keep from the translated subsets - the twelve A4 worked in, by script.
INDIC_COLS = ["hin_Deva", "mar_Deva", "tel_Telu", "ben_Beng", "tam_Taml", "kan_Knda",
              "guj_Gujr", "mal_Mlym", "pan_Guru", "ory_Orya", "asm_Beng", "urd_Arab"]

GUTENBERG_IDS = [1342, 11, 84, 1661, 2701, 98]   # all long out-of-copyright works


def docid(lane, text):
    """Content-addressed id: the same text always yields the same id, on any machine."""
    return f"{lane}-{hashlib.sha256(text.encode('utf-8')).hexdigest()[:12]}"


def clean(t):
    if not t:
        return ""
    return t.replace("\r\n", "\n").replace("\r", "\n").strip()


def stream(repo, split, cfg=None):
    from datasets import load_dataset
    return load_dataset(repo, cfg, split=split, streaming=True)


# --------------------------------------------------------------------------- lanes

def lane_web():
    """wikitext ships one row per line; regroup into articles on the ' = Title = ' heading."""
    head = re.compile(r"^ = [^=].* = $")
    buf, title = [], None
    for ex in stream("Salesforce/wikitext", "train", "wikitext-103-raw-v1"):
        line = ex.get("text") or ""
        if head.match(line.rstrip("\n")):
            if buf and title:
                body = clean("".join(buf))
                if len(body) > 400:
                    yield {"text": body, "meta": {"title": title}}
            title, buf = line.strip(" =\n"), []
        else:
            buf.append(line)
    if buf and title:
        body = clean("".join(buf))
        if len(body) > 400:
            yield {"text": body, "meta": {"title": title}}


def lane_code():
    """Permissive licences only. Each file's licence and repo travel with it into the manifest."""
    for ex in stream("codeparrot/codeparrot-clean-valid", "train"):
        lic = (ex.get("license") or "").lower()
        if lic not in PERMISSIVE or ex.get("autogenerated"):
            continue
        body = clean(ex.get("content"))
        if len(body) < 200:
            continue
        yield {"text": body, "meta": {"licence": lic,
                                      "repo": ex.get("repo_name"),
                                      "path": ex.get("path")}}


def lane_math():
    for ex in stream("open-web-math/open-web-math", "train"):
        body = clean(ex.get("text"))
        if len(body) > 300:
            yield {"text": body, "meta": {}}


def lane_reasoning():
    """GSM8K with an explicit prompt/answer split, so packing can mask the prompt.

    Emitted ONCE per example. A5 section 9.2 lost a published finding because the proxy repeated
    this source before splitting a validation set off by token offset, leaking 100% of it. The
    lesson is encoded here: never repeat a source before the split.
    """
    for ex in stream("openai/gsm8k", "train", "main"):
        q, a = clean(ex.get("question")), clean(ex.get("answer"))
        if not q or not a:
            continue
        yield {"spans": [{"role": "prompt", "text": f"Question: {q}\nAnswer:", "loss": 0},
                         {"role": "answer", "text": f" {a}", "loss": 1}],
               "meta": {}}


def _pairs(cell):
    """indic-align stores [[prompt, response], ...]; tolerate the odd malformed row."""
    out = []
    if not isinstance(cell, list):
        return out
    for turn in cell:
        if isinstance(turn, (list, tuple)) and len(turn) >= 2:
            p, r = clean(str(turn[0])), clean(str(turn[1]))
            if p and r:
                out.append((p, r))
    return out


def _band(text, register):
    """Difficulty band by register and length - the question the lecture raised and left open.

    The lecture asked whether Indic should start on simple news or on RBI and legal material. The
    answer here is that register decides it: short conversational exchanges are the easy end, and
    long procedural material - the WikiHow-style step-by-step register that legal and regulatory
    text most resembles - is the hard end. The curriculum stages in plan.json then gate Indic the
    same way they gate every other lane.

    Thresholds come from the measured length distribution of this corpus (discussion median ~420
    chars, instructional median ~3000), not from round numbers. An earlier cut used a flat 2500
    and put 93% of the lane in a single band, which would have made stage gating a no-op.
    """
    if register == "instructional":
        return "B4" if len(text) > 3000 else "B3"
    if len(text) < 250:
        return "B1"
    return "B2" if len(text) < 600 else "B3"


# Indic script ranges, by codepoint. Used to keep the Indic lane actually Indic - see the note
# in lane_indic() for why that guard exists.
INDIC_RANGES = [(0x0900, 0x097F), (0x0980, 0x09FF), (0x0A00, 0x0A7F), (0x0A80, 0x0AFF),
                (0x0B00, 0x0B7F), (0x0B80, 0x0BFF), (0x0C00, 0x0C7F), (0x0C80, 0x0CFF),
                (0x0D00, 0x0D7F), (0x0600, 0x06FF)]

# subset -> (tier, register, share of the Indic byte budget)
INDIC_PLAN = [("Anudesh", "native", "discussion", 0.30),
              ("WikiHow", "translated", "instructional", 0.35),
              ("Dolly_T", "translated", "discussion", 0.35)]


def indic_ratio(text):
    letters = [c for c in text[:2000] if c.isalpha()]
    if not letters:
        return 0.0
    hits = sum(1 for c in letters if any(lo <= ord(c) <= hi for lo, hi in INDIC_RANGES))
    return hits / len(letters)


def lane_indic():
    """Three subsets, each on its own slice of the byte budget, all gated on Indic script.

    Two guards here were added after measuring what the naive version produced, and both matter.

    The *budget split* exists because taking documents greedily in stream order filled the entire
    lane from Anudesh and never reached the translated subsets - which would have thrown away the
    provenance tier A5 section 8.2 depended on. Without a native/translated label A5 could not have
    separated native Indic from synthetic, and would still believe more Indic was free.

    The *script gate* exists because Anudesh is overwhelmingly English: unfiltered, this lane came
    out 95% Latin characters and only 11% of documents were majority Indic script. An Indic lane
    made of English would quietly defeat the thing it exists to demonstrate, because the protected
    floor in plan.json is there precisely to stop an English-centric OPUS scorer discarding Indic.
    A lane that is already English would never be discarded, and the demo would prove nothing.
    """
    budget_total = CAPS["indic"]
    for cfg, tier, register, share in INDIC_PLAN:
        budget, spent, row = int(budget_total * share), 0, 0
        for ex in stream("ai4bharat/indic-align", "train", cfg):
            if spent >= budget:
                break
            if cfg == "Anudesh":
                pairs = [(p, r, None) for p, r in _pairs(ex.get("interactions"))]
            else:
                # One language per row, rotating, so no single language dominates the lane.
                col = INDIC_COLS[row % len(INDIC_COLS)]
                pairs = [(p, r, col) for p, r in _pairs(ex.get(col))]
            row += 1
            for p, r, col in pairs:
                body = f"{p}\n\n{r}"
                if indic_ratio(body) < 0.35:
                    continue
                meta = {"tier": tier, "subset": cfg, "register": register,
                        "band": _band(body, register)}
                if col:
                    meta["lang"] = col
                yield {"text": body, "meta": meta}
                spent += len(body)
                if spent >= budget:
                    break


AGENT_MARK = re.compile(r"(USER:|ASSISTANT:|FUNCTION RESPONSE:)")


def lane_agentic():
    """Parse a Glaive chat into role spans, which is what makes the loss mask real.

    Only ASSISTANT spans carry loss. The system prompt (a wall of function schemas), the user
    turns and the tool output are context the model reads but is not trained to produce. That is
    where plan.json's trainable_frac of 0.35 for this lane comes from - the demo measures it
    rather than asserting it.
    """
    for ex in stream("glaiveai/glaive-function-calling-v2", "train"):
        chat = clean(ex.get("chat"))
        sysmsg = clean(ex.get("system"))
        if not chat:
            continue
        spans = []
        if sysmsg:
            spans.append({"role": "system", "text": sysmsg, "loss": 0})
        parts = AGENT_MARK.split(chat)
        # split() leaves any pre-marker text at index 0; markers and bodies alternate after it.
        for i in range(1, len(parts) - 1, 2):
            marker, body = parts[i], clean(parts[i + 1]).replace("<|endoftext|>", "").strip()
            if not body:
                continue
            role = {"USER:": "user", "ASSISTANT:": "assistant",
                    "FUNCTION RESPONSE:": "tool"}[marker]
            spans.append({"role": role, "text": body, "loss": 1 if role == "assistant" else 0})
        if any(s["loss"] for s in spans):
            yield {"spans": spans, "meta": {}}


PG_START = re.compile(r"\*\*\*\s*START OF TH(E|IS) PROJECT GUTENBERG EBOOK.*?\*\*\*", re.S)
PG_END = re.compile(r"\*\*\*\s*END OF TH(E|IS) PROJECT GUTENBERG EBOOK.*?\*\*\*", re.S)


def lane_long_ctx():
    """Whole books, chunked to chapter scale.

    Naturally long documents are the constraint this lane exists to model - A5 section 3.2 makes
    that point - so the unit here is a large contiguous passage, not a paragraph. Chunks land
    around 15-30K tokens, which is what exercises multi-document packing at long sequence length.
    """
    for bid in GUTENBERG_IDS:
        url = f"https://www.gutenberg.org/cache/epub/{bid}/pg{bid}.txt"
        req = urllib.request.Request(url, headers={"User-Agent": "erav5-assignment6/1.0"})
        with urllib.request.urlopen(req, timeout=120) as fh:
            raw = fh.read().decode("utf-8", errors="replace")
        m1, m2 = PG_START.search(raw), PG_END.search(raw)
        body = clean(raw[m1.end():m2.start()] if m1 and m2 else raw)
        for i in range(0, len(body), 60_000):
            chunk = body[i:i + 60_000]
            if len(chunk) > 10_000:
                yield {"text": chunk, "meta": {"gutenberg_id": bid, "chunk": i // 60_000}}


LANES = {
    "web": lane_web, "code": lane_code, "math": lane_math, "reasoning": lane_reasoning,
    "indic": lane_indic, "agentic": lane_agentic, "long_ctx": lane_long_ctx,
}


# --------------------------------------------------------------------------- writing

def write_lane(lane):
    cap = CAPS[lane]
    path = os.path.join(OUT, f"{lane}.jsonl")
    seen, n, size = set(), 0, 0
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        for rec in LANES[lane]():
            body = rec.get("text") or "".join(s["text"] for s in rec.get("spans", []))
            if not body:
                continue
            did = docid(lane, body)
            if did in seen:                     # exact-duplicate guard, cheap and deterministic
                continue
            seen.add(did)
            doc = {"id": did, "lane": lane, "meta": rec.get("meta", {}), "chars": len(body)}
            if "spans" in rec:
                doc["spans"] = rec["spans"]
            else:
                doc["text"] = rec["text"]
            fh.write(json.dumps(doc, ensure_ascii=False, sort_keys=True,
                                separators=(",", ":")) + "\n")
            n += 1
            size += len(body)
            if size >= cap:
                break
    digest = hashlib.sha256(io.open(path, "rb").read()).hexdigest()
    src, lic = LICENCES[lane]
    print(f"  {lane:10} {n:6d} docs  {size/1e6:5.2f} MB raw  sha256 {digest[:16]}...")
    return {"lane": lane, "source": src, "licence": lic, "docs": n, "raw_chars": size,
            "file": f"{lane}.jsonl", "bytes": os.path.getsize(path), "sha256": digest}


def main():
    want = sys.argv[1:] or list(LANES)
    idx_path = os.path.join(OUT, "SOURCES.json")
    index = {}
    if os.path.exists(idx_path):
        index = {e["lane"]: e for e in json.load(io.open(idx_path, encoding="utf-8"))["lanes"]}

    print(f"fetching {len(want)} lane(s) -> {OUT}")
    for lane in want:
        if lane not in LANES:
            print(f"  !! unknown lane: {lane}")
            continue
        try:
            index[lane] = write_lane(lane)
        except Exception as exc:
            print(f"  !! {lane} FAILED: {repr(exc)[:200]}")

    payload = {
        "_note": ("Frozen corpus slices committed so run_demo.py reproduces offline. Each lane "
                  "keeps its own licence; see ../../NOTICE.md. run_demo.py verifies these hashes "
                  "before building shards and aborts on mismatch."),
        "lanes": [index[k] for k in LANES if k in index],
    }
    io.open(idx_path, "w", encoding="utf-8", newline="\n").write(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    print(f"wrote {idx_path}")


if __name__ == "__main__":
    main()
