"""
Build the evidence bundle: `evidence.json` and `evidence.md`.

The brief is explicit that hardcoded evidence will not be accepted, so every row here is a
**verdict computed from an artefact**, and every row names the file a reader can open to check it.
Nothing in this module decides whether something passed; it only formats what the audit measured.

The nine rows are the ones the brief names.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ART, write_json

# The nine requirements the brief names, in the order the brief lists them, using the brief's own
# wording for the Evidence column. Fork is appended as a tenth: it is a required demonstrable
# ("forking from an earlier checkpoint") but is not one of the nine rows in the brief's table, so it
# goes after them rather than disturbing an order a reviewer will be ticking off.
ROWS = [
    ("tokenizer_integrity", "Tokenizer integrity", "Manifest record",
     "manifests/manifest.json"),
    ("evaluation_firewall", "Evaluation firewall", "Blocked-shard event",
     "ledgers/firewall.jsonl"),
    ("packing_correctness", "Packing correctness", "Packed-batch report",
     "ledgers/consumption.jsonl"),
    ("mixture_compliance", "Mixture compliance", "Planned versus actual shares",
     "ledgers/consumption.jsonl"),
    ("opus_audit_trail", "OPUS audit trail", "Candidate decision records",
     "ledgers/opus.jsonl"),
    ("crash_recovery", "Crash recovery", "Expected and resumed batch ids",
     "ledgers/consumption.crash.jsonl"),
    ("replay", "Replay", "Original and replay hashes",
     "ledgers/consumption.jsonl"),
    ("learning_trace", "Learning trace", "Loss linked to source data",
     "ledgers/learning.jsonl"),
    ("throughput", "Throughput", "Performance report",
     "performance.json"),
    ("fork", "Fork from an earlier checkpoint", "Parent prefix and post-fork divergence",
     "ledgers/consumption.fork.jsonl"),
]


def build(results):
    """results: key -> {"pass": bool, "detail": str, "data": {...}}"""
    rows = []
    for key, label, what, where in ROWS:
        r = results.get(key, {"pass": False, "detail": "not evaluated"})
        rows.append({"requirement": label, "key": key,
                     "result": "PASS" if r.get("pass") else "FAIL",
                     "evidence": what, "evidence_file": where,
                     "detail": r.get("detail", ""),
                     "data": r.get("data", {})})
    n_pass = sum(1 for r in rows if r["result"] == "PASS")
    bundle = {
        "_note": ("Generated by src/evidence.py from the artefacts in this directory. Every verdict "
                  "is computed from a ledger, manifest or report that ships alongside it; none is "
                  "written by hand. Re-run `python run_demo.py` to regenerate the whole bundle."),
        "summary": {"requirements": len(rows), "passed": n_pass, "failed": len(rows) - n_pass,
                    "all_passed": n_pass == len(rows)},
        "requirements": rows,
    }
    return bundle


def render_md(bundle, extras=None):
    """Human-readable summary, in sections, in the order a reviewer will check them."""
    s = bundle["summary"]
    out = [
        "# Evidence bundle",
        "",
        "Assignment 6 - Training Data Execution System. Generated by `src/evidence.py` from the "
        "artefacts in this directory; no verdict below is written by hand.",
        "",
        f"**Result: {s['passed']}/{s['requirements']} requirements passed.**",
        "",
        "Regenerate everything with `python run_demo.py` from the repository root of "
        "`assignment-6/`.",
        "",
        "---",
        "",
        "## 1. Requirement results",
        "",
        "| # | Requirement | Result | Evidence |",
        "|---:|---|:---:|---|",
    ]
    for i, r in enumerate(bundle["requirements"], 1):
        out.append(f"| {i} | {r['requirement']} | **{r['result']}** | {r['evidence']} |")
    out += [
        "",
        "## 2. Where each result can be verified",
        "",
        "| # | Requirement | File |",
        "|---:|---|---|",
    ]
    for i, r in enumerate(bundle["requirements"], 1):
        out.append(f"| {i} | {r['requirement']} | `{r['evidence_file']}` |")
    out += ["", "## 3. What each result means", ""]
    for i, r in enumerate(bundle["requirements"], 1):
        out.append(f"**{i}. {r['requirement']} - {r['result']}**")
        out.append("")
        out.append(f"{r['detail']}")
        out.append("")
    if extras:
        out += ["---", ""] + extras
    return "\n".join(out) + "\n"


def save(bundle, extras=None):
    write_json(os.path.join(ART, "evidence.json"), bundle)
    path = os.path.join(ART, "evidence.md")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_md(bundle, extras))
    return path
